# Generated by Django 3.1.4 on 2021-04-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.IntegerField()),
                ('date', models.DateField()),
                ('account_no', models.IntegerField()),
                ('supplier_id', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=200)),
                ('total_amount', models.FloatField()),
            ],
        ),
    ]
