# Generated by Django 3.1.6 on 2021-04-15 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=250)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('diagnosis', models.TextField()),
                ('clinical_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.clinicalbook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doug_id', models.IntegerField()),
                ('doug_name', models.CharField(max_length=250)),
                ('dose', models.IntegerField()),
                ('time', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Morning', 'Morning')], default='Morning', max_length=30)),
                ('duration', models.IntegerField()),
                ('duration_text', models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month')], default='Day', max_length=25)),
                ('clinical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.clinicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('clinical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.clinicalrecord')),
            ],
        ),
    ]
