# Generated by Django 3.1.6 on 2021-04-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='status',
            field=models.CharField(choices=[('Queue', 'In Queue'), ('Start Processing', 'Start Processing'), ('Complete', 'Completed')], default='Queue', max_length=20),
        ),
    ]
