# Generated by Django 3.1.6 on 2021-04-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_auto_20210415_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='lab_report_id',
            field=models.CharField(default=-1, max_length=250),
        ),
    ]
