# Generated by Django 3.1.6 on 2021-04-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_labreport_lab_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='time',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Morning', 'Morning'), ('Full Day', 'Full Day')], default='Morning', max_length=30),
        ),
    ]
