# Generated by Django 3.1.6 on 2021-04-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms_deductions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deduction',
            options={'ordering': ['created_at']},
        ),
    ]
