# Generated by Django 3.1.6 on 2021-03-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams_client_leave_request', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='allowance',
            new_name='ams_client_leave_request',
        ),
    ]
