# Generated by Django 3.1.6 on 2021-04-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_client_leave_request', '0002_auto_20210316_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ams_client_leave_request',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='ams_client_leave_request',
            name='reason',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
