# Generated by Django 3.1.6 on 2021-04-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_client_leave_request', '0003_auto_20210410_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ams_client_leave_request',
            name='leaveDate',
            field=models.DateField(),
        ),
    ]
