# Generated by Django 3.1.6 on 2021-04-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendnce_tracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attendnce_tracker',
        ),
    ]
