# Generated by Django 3.1.6 on 2021-04-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_delete_attendnce_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendnce_tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
