# Generated by Django 3.1.6 on 2021-04-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20210419_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark_attendance_manual',
            name='outTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
