# Generated by Django 3.1.6 on 2021-04-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20210419_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark_attendance_manual',
            name='outTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
