# Generated by Django 3.1.6 on 2021-04-15 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=250)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('nic', models.CharField(blank=True, max_length=250, null=True)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(choices=[('A +', 'A Positive'), ('A -', 'A Negative'), ('B +', 'B Positive'), ('B -', 'B Negative'), ('O +', 'O Positive'), ('O -', 'O Negative'), ('AB +', 'Ab Positive'), ('AB -', 'Ab Negative'), ('N/A', 'Na')], default='N/A', max_length=5)),
                ('address', models.TextField()),
                ('guardian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.guardian')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
