# Generated by Django 3.1.6 on 2021-04-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms_allowances', '0002_auto_20210304_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowance',
            options={'ordering': ['date_created']},
        ),
    ]
