# Generated by Django 3.1.4 on 2021-04-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('inflow_description', models.CharField(max_length=100)),
                ('inflow_amount', models.IntegerField()),
                ('outflow_description', models.CharField(max_length=100)),
                ('outflow_amount', models.IntegerField()),
            ],
        ),
    ]
