# Generated by Django 3.1.6 on 2021-02-26 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spe_title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_f_name', models.CharField(max_length=200)),
                ('emp_s_name', models.CharField(max_length=200)),
                ('emp_dob', models.DateField()),
                ('emp_address_one', models.CharField(max_length=300)),
                ('emp_address_two', models.CharField(max_length=300)),
                ('emp_address_three', models.CharField(max_length=300)),
                ('emp_nic', models.CharField(max_length=15)),
                ('emp_email', models.EmailField(max_length=200, unique=True)),
                ('emp_created_at', models.DateTimeField(auto_now_add=True)),
                ('emp_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthProfessionalsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpt_title', models.CharField(max_length=300)),
                ('hpt_created_at', models.DateTimeField(auto_now_add=True)),
                ('hpt_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mu_title', models.CharField(max_length=200)),
                ('mu_created_at', models.DateTimeField(auto_now_add=True)),
                ('mu_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_name', models.CharField(max_length=200, unique=True)),
                ('sg_basic_salary', models.FloatField()),
                ('sg_hr_rate', models.FloatField(default=0)),
                ('sg_created_at', models.DateTimeField(auto_now_add=True)),
                ('sg_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NursingOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nf_maximum_qualification', models.CharField(max_length=300)),
                ('nf_is_assign', models.BooleanField(default=False)),
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee_management_system.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_designation', models.CharField(max_length=300)),
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee_management_system.employee')),
                ('mu_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employee_management_system.managementunit')),
            ],
        ),
        migrations.CreateModel(
            name='HealthProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp_maximum_qualification', models.CharField(max_length=300)),
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee_management_system.employee')),
                ('hpt_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employee_management_system.healthprofessionalstype')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='sg_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employee_management_system.salarygroup'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_degree', models.CharField(max_length=200)),
                ('d_university', models.CharField(max_length=200)),
                ('d_moh_reg_number', models.CharField(max_length=20, unique=True)),
                ('d_max_patont_count', models.IntegerField(default=0)),
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee_management_system.employee')),
                ('spe_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employee_management_system.doctorspecialization')),
            ],
        ),
    ]
