# Generated by Django 3.1.6 on 2021-02-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_system', '0002_nursingofficer_r_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='d_max_patont_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
