# Generated by Django 3.1.6 on 2021-02-28 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_system', '0005_auto_20210227_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarygroup',
            name='sg_hr_rate',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
