# Generated by Django 3.1.6 on 2021-02-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_system', '0002_nursingofficer_r_id'),
        ('shift_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='s_employee_shift',
            field=models.ManyToManyField(to='employee_management_system.Employee'),
        ),
    ]
