# Generated by Django 3.1.6 on 2021-04-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management_system', '0002_shift_s_employee_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='s_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
