# Generated by Django 3.1.6 on 2021-04-12 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_system', '0007_auto_20210228_1505'),
        ('shift_management_system', '0003_shift_s_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='s_employee_shift',
        ),
        migrations.AddField(
            model_name='shift',
            name='s_employee_shift',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='employee_management_system.employee'),
        ),
    ]
