# Generated by Django 3.1.6 on 2021-02-26 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=200, unique=True)),
                ('r_size', models.FloatField()),
                ('r_location', models.CharField(max_length=350)),
                ('r_created_at', models.DateTimeField(auto_now_add=True)),
                ('r_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllocationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=30)),
                ('at_slot', models.CharField(max_length=15)),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='room_management_system.room')),
            ],
            options={
                'unique_together': {('at_day', 'at_slot', 'r_id')},
            },
        ),
    ]
